"""initial_schema

Revision ID: 62628fe45859
Revises: 
Create Date: 2026-03-03 15:24:43.791052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62628fe45859'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pace_customer_cache',
    sa.Column('customer_id', sa.String(length=8), nullable=False),
    sa.Column('cust_name', sa.String(length=255), nullable=True),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=6), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=60), nullable=True),
    sa.Column('customer_status', sa.String(length=1), nullable=True),
    sa.Column('contact_first_name', sa.String(length=100), nullable=True),
    sa.Column('contact_last_name', sa.String(length=100), nullable=True),
    sa.Column('account_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('pace_job_cache',
    sa.Column('job_number', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=8), nullable=True),
    sa.Column('admin_status', sa.String(length=1), nullable=True),
    sa.Column('date_setup', sa.Date(), nullable=True),
    sa.Column('promise_date', sa.Date(), nullable=True),
    sa.Column('scheduled_ship_date', sa.Date(), nullable=True),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.Column('csr_id', sa.Integer(), nullable=True),
    sa.Column('po_num', sa.String(length=50), nullable=True),
    sa.Column('contact_first_name', sa.String(length=100), nullable=True),
    sa.Column('contact_last_name', sa.String(length=100), nullable=True),
    sa.Column('job_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_parts', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('job_number')
    )
    op.create_table('pace_po_cache',
    sa.Column('po_number', sa.String(length=8), nullable=False),
    sa.Column('pace_internal_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.String(length=8), nullable=True),
    sa.Column('customer_id', sa.String(length=8), nullable=True),
    sa.Column('order_status', sa.String(length=1), nullable=True),
    sa.Column('order_total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('date_entered', sa.Date(), nullable=True),
    sa.Column('date_confirmed', sa.Date(), nullable=True),
    sa.Column('date_last_receipt', sa.Date(), nullable=True),
    sa.Column('buyer', sa.String(length=24), nullable=True),
    sa.Column('confirmed_by', sa.String(length=24), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_first_name', sa.String(length=100), nullable=True),
    sa.Column('contact_last_name', sa.String(length=100), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('po_number')
    )
    op.create_table('pace_vendor_cache',
    sa.Column('vendor_id', sa.String(length=8), nullable=False),
    sa.Column('contact_first_name', sa.String(length=100), nullable=True),
    sa.Column('contact_last_name', sa.String(length=100), nullable=True),
    sa.Column('contact_title', sa.String(length=200), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('fax_number', sa.String(length=60), nullable=True),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=6), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('customer_number', sa.String(length=32), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'user', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('open', 'pending', 'resolved', 'closed', name='threadstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_conversation_id'), 'threads', ['conversation_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='emaildirection'), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_emails', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('import_source', sa.Enum('realtime', 'historical', name='importsource'), nullable=False),
    sa.Column('raw_headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_job_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('job_number', sa.String(length=12), nullable=False),
    sa.Column('link_source', sa.Enum('auto', 'manual', name='linksource'), nullable=False),
    sa.Column('linked_by', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_po_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=8), nullable=False),
    sa.Column('link_source', sa.Enum('auto', 'manual', name='linksource'), nullable=False),
    sa.Column('linked_by', sa.Integer(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('attachment_type', sa.Enum('proof', 'tracking', 'general', name='attachmenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('received', 'sent_for_approval', 'approved', 'rejected', 'revision_requested', name='proofstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proof_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('received', 'sent_for_approval', 'approved', 'rejected', 'revision_requested', name='proofstatus'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proof_history')
    op.drop_table('proofs')
    op.drop_table('attachments')
    op.drop_table('thread_po_links')
    op.drop_table('thread_job_links')
    op.drop_table('notes')
    op.drop_table('emails')
    op.drop_index(op.f('ix_threads_conversation_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('pace_vendor_cache')
    op.drop_table('pace_po_cache')
    op.drop_table('pace_job_cache')
    op.drop_table('pace_customer_cache')
    # ### end Alembic commands ###
