"""add_job_product_type_quoted_price_qty_ordered

Revision ID: 76c4b69758c4
Revises: 62628fe45859
Create Date: 2026-03-06 16:37:48.461855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c4b69758c4'
down_revision: Union[str, None] = '62628fe45859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
